server:
  port: 12347
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.11.110:8849,10.10.11.101:8849,10.10.11.102:8849
        namespace: d2eb05e6-c551-48ad-b66a-5fa7a5473c53
  datasource:
    url: jdbc:mysql://localhost:3306/seata_storage?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 200
      max-wait: 30000
      initial-size: 5
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-while-idle: true
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
  application:
    name: seata-product
seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  registry:
    nacos:
      server-addr: 10.10.11.110:8849,10.10.11.101:8849,10.10.11.102:8849
      namespace: d2eb05e6-c551-48ad-b66a-5fa7a5473c53
      group: SEATA_GROUP
    type: nacos
  config:
    nacos:
      server-addr: 10.10.11.110:8849,10.10.11.101:8849,10.10.11.102:8849
      namespace: d2eb05e6-c551-48ad-b66a-5fa7a5473c53
      group: SEATA_GROUP
  service:
    vgroup-mapping:
      seata-product-group: default