server:
  port: 12346
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.8.2:8848
        namespace: cd1456fd-6a7f-4dc6-bf02-84ea03c8958f
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 200
      max-wait: 30000
      initial-size: 5
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-while-idle: true
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
  application:
    name: seata-order
seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  registry:
    nacos:
      server-addr: 10.10.8.2:8848
      namespace: cd1456fd-6a7f-4dc6-bf02-84ea03c8958f
    type: nacos
  service:
    vgroup-mapping:
      seata-order-group: default